//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailChecker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MailChecker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0-mail.com
        ///027168.com
        ///0815.ru
        ///0815.ry
        ///0815.su
        ///0845.ru
        ///0clickemail.com
        ///0wnd.net
        ///0wnd.org
        ///0x207.info
        ///1-8.biz
        ///100likers.com
        ///10mail.com
        ///10mail.org
        ///10minut.com.pl
        ///10minutemail.cf
        ///10minutemail.co.uk
        ///10minutemail.co.za
        ///10minutemail.com
        ///10minutemail.de
        ///10minutemail.ga
        ///10minutemail.gq
        ///10minutemail.ml
        ///10minutemail.net
        ///10minutesmail.com
        ///10x9.com
        ///123-m.com
        ///12houremail.com
        ///12minutemail.com
        ///12minutemail.net
        ///140unichars.com
        ///147.cl
        ///14n.co.uk
        ///1ce.us
        ///1chuan.com
        ///1fsdfdsfsdf.tk
        ///1mail.ml
        ///1pa [rest of string was truncated]&quot;;.
        /// </summary>
        public static string disposable {
            get {
                return ResourceManager.GetString("disposable", resourceCulture);
            }
        }
    }
}
